### ISSUE TITLE
Working with Code, week 1, Sunday Roll Call

### ISSUE THREAD

**Issue by colevandersWands** [HackYourFutureBelgium/class-11-12#1]
## Roll Call!

Leave us a comment with these two things:

1. A summary of your week using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by iLienstAr** [comment]
💻 🤗 🤩 
Welcome Class 11 & 12! I am happy you can finally start your HackYourFuture adventure!

**Comment by sharafcs50** [comment]
1) Went through the Pre course material, Reviewed GIT commands, linux commands, set up WSL and had everything ready and good to go.
2) Im excited to get going with the course.

**Comment by colevandersWands** [comment]
1. 🥚 🐣 🐥 
2. Welcome! Week 1 of many :)

**Comment by otagi** [comment]
💻 ☀️ 🍦 🚲  📺 
Welcome! Since we're starting with Markdown, check out [John Gruber’s blog](https://daringfireball.net)! (he’s the original Markdown creator)

**Comment by himanshisaxena** [comment]
1. Everything installed successfully .
2. I am super excited to join the class.

**Comment by emelysalmeron** [comment]
1. 😧  ❎ 🔱 😟 ⁉️  📲 👩 ✅ 💻 💥 🌟 😵 💗😃
2. Super happy to be part of this course :D 
--

**Comment by sabanyelkenci** [comment]
Hi everyone

**Comment by bermarte** [comment]
Hello **HYF**! :blush: :walking: :cookie: :pencil: :calling:

**Comment by DIVYASREE345** [comment]
1. 😄 😕 👪 😆 
2.HAPPY AND WORRIED.

**Comment by krakla** [comment]
Hello :)

**Comment by maniiasov** [comment]
Hello!!!

**Comment by Atinos31** [comment]
hi

**Comment by samirm00** [comment]
😊 very excited

**Comment by lauraramirez220612** [comment]
Good morning,   my last week has been full of duties, here I was putting all my tasks ending or some momentaneouslly putting on ice. Normally I take cnederlands classes all mornings from Monday to Thursday.

**Comment by sashinskaya** [comment]
:) hey there!

**Comment by Moon-NguyetDuong** [comment]
1. 🥚 🐣  👍 
2. So excited to start the coding journey and nervous at the same time :)

**Comment by AnisyaPurnama** [comment]
1. :thinking: :grimacing: :star_struck: :sparkling_heart:
2. Surprisingly fun!

**Comment by preeti-t** [comment]
Hello.

**Comment by Houcinos** [comment]
1/ 👍
2/ Looking forward to it

**Comment by Ina-arpine** [comment]
hi

**Comment by KrystynaMil** [comment]
hi and thank you

**Comment by jraoul2002** [comment]
hi everybody :)

**Comment by tahminarasoli** [comment]
hello there,

**Comment by businan** [comment]
I am waiting to start

**Comment by peymanshahmarimikaeeldarehsi** [comment]
test comment 💯

**Comment by maniiasov** [comment]
👍

**Comment by rago89** [comment]
thanks is already activated

**Comment by Atinos31** [comment]
``🙄🤔😶

**Comment by 22count22** [comment]
😀🥰🤗

**Comment by Brainketunze** [comment]
:thumbsup: :clap: :simple_smile:

**Comment by LiubovPlugar** [comment]
👋
