### ISSUE TITLE
Marie Belyse : UX/UI design 

### ISSUE THREAD

**Issue by MarieBelyse** [HackYourFutureBelgium/class-11-12#108]
## Roll Call!

Leave us a comment with these two things:

1. A summary of your week using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

This week was good experience  to me I learnt a lot by working as team on GitHub

**Comment by iLienstAr** [comment]
Hey @MarieBelyse, you've created your own Roll Call again.
That's not what you're supposed to do 😉 

What we expect you to do every Sunday before class is that you give a *comment* on the Roll Call issue that we post in Slack before class.
Tell me if it is not clear. 🙏

**Comment by MarieBelyse** [comment]
Thanks Lien I understand now next Sunday I will do it correctly.On 18 Oct 2020 14:58, Lien Arits <notifications@github.com> wrote:

Hey @MarieBelyse, you've created your own Roll Call again.

That's not what you're supposed to do 😉

What we expect you to do every Sunday before class is that you give a comment on the Roll Call issue that we post in Slack before class.

Tell me if it is not clear. 🙏

**Comment by samirm00** [comment]
@MarieBelyse  Hello Marie , you  can use this issue for your homework , kind regards,
