### ISSUE TITLE
Debugging, week 1, Sunday Roll Call

### ISSUE THREAD

**Issue by MarieBelyse** [HackYourFutureBelgium/class-11-12#144]
## Roll Call!

Leave us a comment with these two things:

1. A summary of your week using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)
My week was nice by learning a lot about Figma and watching different JS tutors

**Comment by iLienstAr** [comment]
Hey @MarieBelyse you should not open this Roll Call issue.

The purpose of the Roll Call that Evan posts is to *comment* on it and tell about your week.

**Comment by samirm00** [comment]
this fixes#144
