### ISSUE TITLE
rago89: debugging

### ISSUE THREAD

**Issue by rago89** [HackYourFutureBelgium/class-11-12#164]
## Suggested Study

Helpful resources for this module

- [study.hackyourfuture.be/javascript](https://study.hackyourfuture.be/javascript)

### compute-it.toxicode

- [x] [the game](http://compute-it.toxicode.fr/) (_**highly** recommended_)
- [x] [about the game](http://compute-it.toxicode.fr/about.html)

### What is JavaScript?

- [x] [Andrew Mosh](https://www.youtube.com/watch?v=upDLs1sn7g4)
- [x] [Code School](https://www.youtube.com/watch?v=nItSSTwBvSU)
- [x] [MDN: First Steps](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript)
- [ ] [javascript.info](https://javascript.info/intro)
- [ ] [Danielle Thé](https://www.youtube.com/watch?v=gT0Lh1eYk78)

### Debugging Tools

- [x] [Errors & Debugging](https://education.launchcode.org/intro-to-professional-web-dev/chapters/errors-and-debugging/index.html)
- [x] [Developer Console](https://javascript.info/devtools)
- [x] [Debugging in Chrome](https://javascript.info/debugging-chrome)
  - [breakpoints](https://developers.google.com/web/tools/chrome-devtools/javascript/reference)
- [ ] [Debugging in FireFox](https://developer.mozilla.org/en-US/docs/Tools/Debugger)
- [ ] [pythontutor.com](http://pythontutor.com/) -> [JS Tutor](http://pythontutor.com/javascript.html)

### ISOLATED
- [x] Variables
- [x] Value-swaps
- [x]  Primitive-types
- [x] Comparing-and-asserting
- [x] Explicit-coercion
- [x] Logical-operators
- [x] Block-scope
- [x] Conditionals
- [x] Comparisons
- [x] Arithmetic
- [x] While-loops
- [x] Break-continue
- [x] Increment-decrement
- [x] For-loops
- [x] Functions
- [x] The-callstack

### INTERACT

- [x] Prompt-alert-confirm
- [x] User-flow
---
- [x]  Integrate

- [ ]  Separate

- [ ]   Studying-javascript

---

## Week II

- [x] Sunday Prep

- [x] Sunday Class

### Project
 [Group Project](https://github.com/HackYourFutureBelgium/class-11-12/issues/169)

### Check-In

__Progress__
Studying Functions 
__Blocked__
I've been a little bit sick, but today I feel better and warming up the engine 
__Next Steps__
Still missing some topics from last week and start getting ready for Sunday 
__Tip(s) of the week__
Understand well functions and loops
---

## Week III

- [ ] Sunday Prep

- [ ] Sunday Class

### Project
 [Group Project](https://github.com/HackYourFutureBelgium/class-11-12/issues/169)

### Check-In

__Progress__
missing some exercises on input-output-loops and   Iterating user data 
__Blocked__
 
__Next Steps__
Try to finish all the content 
__Tip(s) of the week__
make templates to get a better understanding
### What went well
Start to understand JavasCript
### What went less well
Health problems
### What to do differently next module
Continue planning the time to get all the task done 
### Shout-Out
Timeeeeee
### Reflections
It's  a difficult module because is a new language to learn, but the good thing is that start by fixing bugs, and it's nice because in time they are not going to be a problem

**Comment by colevandersWands** [comment]
@rago89 , `Health problems` - let us know if you want some extra help making up for time lost.
