### ISSUE TITLE
Anisya: Working With Code

### ISSUE THREAD

**Issue by AnisyaPurnama** [HackYourFutureBelgium/class-11-12#17]
## Suggested Study

- [x] study.hackyourfuture.be/git-and-github
- [x] Creating a GitHub Pages Website
- [x] learngitbranching
- [x] Git & GitHub for Poets
- [x] First Week on GitHub tutorial from lab.github.com
- [x] Getting Started with GitHub
- [x] RogerDudler Git-Guide
- [x] Git & GitHub for Poets: Intro to the Command Line
- [x] Git & GitHub for Poets: Cloning Repo & Push/Pull
- [x] Creating a GitHub Repository
- [x] Creating a local repo and push
- [x] Creating a GitHub Pages site
- [x] Uploading your project to GitHub
- [x] GitKraken: initialize a new project , add remote & push

## Exercises

- [x] [Profile README](https://github.com/your-user-name)
- [x] [Home Page](https://your-user-name.github.io)
- [x] `/hack-my-future` directory on your computer (for keeping your work organized)

---

## Week 1

- [x] Sunday Prep

- [x] Sunday Class

### Progress

Get my README profile and github.io home page done.

### Next Steps
- Do some more exercise to pull changes via GitKraken/ make some changes to my home page.
- Start reading module 2

### Tip(s) of the week
:zipper_mouth_face:
---

### What went well
Making README profile and homepage went well.

### What went less well
Emojis syntax, but thanks to @otagi I figure out using emojis keyboard shortcut.

### What to do differently next module
Read more and spend more time to study.

### Shout-Out
@colevandersWands @otagi 

### Reflections
💭

**Comment by colevandersWands** [comment]
@AnisyaPurnama , you can mark your self as unblocked: sadly the emojis won't show in github pages 😢 

Nice work on the repos and the checkin!

**Comment by AnisyaPurnama** [comment]
@colevandersWands ahh I see.. okay then and thank you! 😉

**Comment by colevandersWands** [comment]
@AnisyaPurnama , did you see @otagi's message in the class channel?  Turns out you can use emojis in GitHub Pages if you copy-paste them into your markdown instead of using the `:emoji:` syntax.  Cooool

**Comment by AnisyaPurnama** [comment]
@colevandersWands yeah it works! thanks @otagi 😁
