### ISSUE TITLE
rago89: behavior-strategy-implementation

### ISSUE THREAD

**Issue by rago89** [HackYourFutureBelgium/class-11-12#184]
> [module repository](_)

## Suggested Study

<details>
<summary>expand/collapse</summary>
<br>

> [study.hackyourfuture.be/javascript](https://study.hackyourfuture.be/javascript)

### Exercises & Practice

- [ ] 🥚,🐣,🐥: [Solution Write-Ups](https://github.com/HackYourFutureBelgium/solution-write-ups) (important!)
- [ ]  🐣: [document-and-pass](https://github.com/HackYourFutureBelgium/document-and-pass)
- [ ]  Study Lense Exercises
- [x]  🥚: [./about-testing](./about-testing)
- [x]  🥚: [./isolate](./isolate)
- [ ] 🥚: [./refactor-and-test](./refactor-and-test)
- [ ]  🐣: [./function-design](./function-design)
- [ ]  🐣: [./user-data](./user-data)
- [ ]  🐥: `./using-errors`: _coming soon_
- [ ]  🐥: [./koans](./koans)
- [ ]  🐣: Integrating JS with HTML & CSS

- [ ]  [4 challenges](https://github.com/HackYourFutureBelgium/debugging-integrate-week-1)
- [ ]  [6 challenges](https://github.com/HackYourFutureBelgium/debugging-project-week-1)
- [ ]  [shared program data](https://github.com/HackYourFutureBelgium/debugging-integrate-week-2)
- [ ]  [user data in an array](https://github.com/HackYourFutureBelgium/testing-integrate-week-1)
- [ ]  [array of numbers](https://github.com/HackYourFutureBelgium/array-of-numbers)
- [ ]  [favorite words](https://github.com/HackYourFutureBelgium/favorite-words)

- 🐥: More Coding Challenges:
- [ ]  [fuzz testing](https://hackyourfuturebelgium.github.io/fuzz)
- [ ]  [rolling-scopes-school](https://github.com/rolling-scopes-school/js-assignments)
- [x]  [Functions and Arrays](https://github.com/ironhack-labs/lab-javascript-functions-and-arrays/)
- [ ]  [Advanced Collection Methods](https://github.com/ironhack-labs/lab-javascript-advanced-collection-methods)
- [ ]  [Native Array Methods](https://github.com/gSchool/native-array-methods-exercises/)
- [ ]  [clue](https://github.com/ironhack-labs/lab-javascript-clue/)
- [ ]  [JavaScript-Koans](https://github.com/HackYourFutureBelgium/JavaScript-Koans/tree/master/src) (1-4)

 ### Reading Code
 - [ ] Done.

### About Testing

- [ ]  [FunFunFunction](https://www.youtube.com/watch?v=Eu35xM76kKY&list=PL0zVEGEvSaeF_zoW9o66wa_UCNE3a7BEr):
- [ ]  Oliverjam

### JS References & Tutorials

- [x]  Reference vs. Values

### Higher-Order Functions

- [x]  Arrays
- [x] Objects
      - `for ... in`
      - Object Transformations
      - Arrays of Objects
- [x] Recursion
</details>

---

## Week I
<details>
<summary>expand/collapse</summary>
<br>

- [x] Sunday Prep

- [x] Sunday Class

### Check-In

__Progress__
studying with callstack in isolated  
__Blocked__
not yet, going slow to try to understand better the code 
__Next Steps__
today I'll be until _functional-array-methods_ and tomorrow _solition-write-ups, Friday getting prepared for Sunday class 
__Tip(s) of the week__
get very clear with reference and values, and swaps
</details>

## Week 2
<details>
<summary>expand/collapse</summary>
<br>

- [x] Sunday Prep

- [x] Sunday Class

### Check-In

__Progress__
  working object transformation exercises 
__Blocked__
   seen more content to finish the second exercise
__Next Steps__
function design, koans, refactor and test 
__Tip(s) of the week__
keep in track keys and values fro objects 
</details>

## Week 3

- [ ] Sunday Prep

- [ ] Sunday Class

### Check-In

__Progress__
  working on Integrating JS with HTML & CSS
__Blocked__
   time lost this week
__Next Steps__
work on the project with teammates, and I want to make a quick review of the module   
__Tip(s) of the week__

### What went well
Understanding better the code, reading, watching videos, and burning a lot of the brain
### What went less well
time lost, hard to keep the balance between studying and home
### What to do differently next module
practice more and read less
### Reflections
Is frustrating, but we have to be constant with the studying, one day or another we are going to master it.

**Comment by colevandersWands** [comment]
> seen more content to finish the second exercise

For which exercises, what type of content would be helpful?

the koans exercises have moved to the `about-testing/exercises` folder and I've added more in there.

**Comment by rago89** [comment]
> > seen more content to finish the second exercise
> 
> For which exercises, what type of content would be helpful?
> 
> the koans exercises have moved to the `about-testing/exercises` folder and I've added more in there.

Sorry for didn't reply yesterday, I took the day off I was very saturated, I started today with the exercises about testing.

**Comment by colevandersWands** [comment]
>  I took the day off I was very saturated

necessary every now and then, no need for sorries.  Happy testing!

**Comment by colevandersWands** [comment]
@rago89 , `time lost this week` let me know if you have any questions or would like some help deciding what to focus on in the next week(s)
