### ISSUE TITLE
Group 1 : behavior-strategy-implementation, week 3

### ISSUE THREAD

**Issue by KrystynaMil** [HackYourFutureBelgium/class-11-12#210]
# Project Name
Group Project, [favorite-word](https://github.com/HackYourFutureBelgium/favorite-word)

- _Group 1_
- _Rafael_( Project leader)
- _Krystyna_(repo owner)
- _Divya_
- _Brain_

- [x] [repo](https://github.com/KrystynaMil/favorite-word) (with a complete README)
- [x] [live demo]( https://krystynamil.github.io/favorite-word/)
- [x] [Figma planning document](_)
- [x] [one issue per .js file](https://github.com/KrystynaMil/favorite-word/issues)
- [x] [project board](https://github.com/KrystynaMil/favorite-word/projects/1)
- [x] [one branch per step](https://github.com/KrystynaMil/favorite-word/settings/branches)
- [x] [one closed PR per step](https://github.com/KrystynaMil/favorite-word/pulls)

**Comment by colevandersWands** [comment]
@rago89, @KrystynaMil , @DIVYASREE345 , @Brainketunze .  A suggestion for setting up your issues, try to make one per tiny task (a single file for example) and then to relate them all together with labels and milestones.  This is different than you learned in Incremental Development, the projects are more complex now so the workflow will change a bit.  more smaller issues will make it easier to see your progress, do code reviews, and ask for help.

I recommend having one label for each folder, and one milestone for each step in the development strategy.  Now imagine having an issue for each file with a label to indicate which folder it is in, and a milestone to indicate which user story it is for. [group 4](https://github.com/AnisyaPurnama/favorite-word-group4/projects/1) is headed in this direction (but without the labels yet)

**Comment by samirm00** [comment]
Dear colleagues   ,
about the group issue labeling :
you only need two labels only :
1- project-3   ,  3 refer to the number of the week
2- group
3- select the milestone of the module

**Comment by samirm00** [comment]
@Brainketunze  also b-s-i is not necessary because , you already have your milestone
