### ISSUE TITLE
rago89: separation-of-concerns

### ISSUE THREAD

**Issue by rago89** [HackYourFutureBelgium/class-11-12#215]
> [module repository](https://github.com/HackYourFutureBelgium/separation-of-concerns/blob/master/README.md)

## Suggested Study

<details>
<summary>expand/collapse</summary>

### Separation of Concerns

- [ ] Separation of Concerns

### Code in this Repo
- [ ] 🥚 [/isolate](./isolate?hyf): focus on the DOM and events, isolating JavaScript in the debugger
- [ ] 🥚 [/integrate](./integrate?hyf): learn how to integrate JS into user interfaces built with HTML and CSS
- [ ] 🥚 [/stepped](./stepped?hyf): study HTML/CSS/JS projects built up step-by-step (only examples)
- [ ] 🥚 [/refactor-and-test](./refactor-and-test?hyf): practice refactoring the logic from user interactions and testing it in isolation
- [ ] 🐣 [/import-export](./import-export?hyf): learn how to use `import` and `export` to separate your code into different files
- [ ] 🥚 [/separated](./separated?hyf): study HTML/CSS/JS projects that have been separated by concern (only examples)
### JavaScript 30
- [ ] [javascript30.com](https://javascript30.com/)
- [ ] [Group Project Guide](https://github.com/HackYourFutureBelgium/javascript-30)
- [ ] [Group Project Starter Repo](https://github.com/HackYourFutureBelgium/javascript-30-starter)

### Repos of practice

 - [ ] [hyfbe/dom-manipulation](https://github.com/HackYourFutureBelgium/dom-manipulation)
 - [ ] [hyfbe/listeners-and-handlers](https://github.com/HackYourFutureBelgium/listeners-and-handlers)
 - [ ] [hyfbe/handler-refactors](https://github.com/HackYourFutureBelgium/handler-refactors)
 - [ ] [hyfbe/using-user-events](https://github.com/HackYourFutureBelgium/using-user-events)

### The DOM

- [ ] Contents about the **Doom**

### Events

- [x] Contents about the **Events**

</details>
<br>

---

## Week I

- [ ] Sunday Prep

- [ ] Sunday Class

### Check-In

__Progress__
starting with the first project of javascript 30 
__Blocked__
reading more content about modules import and export, separate the handlers and listener's but still not work 
__Next Steps__
after the finish, the first project continues to the second one and work on exercises in isolate
__Tip(s) of the week__
set a study plan and try to not skip the listing plan

### Project

 [link to the group issue](https://github.com/HackYourFutureBelgium/class-11-12/issues/237)

---

### Check-In

__Progress__
Working with Group Project
__Blocked__
not yet
__Next Steps__
after the finish the  project I will work on exercises in isolate
__Tip(s) of the week__
Study a lot : )

**Comment by colevandersWands** [comment]
> reading more content about modules import and export, separate the handlers and listener's but still not work

@rago89, if you push the code you're blocked on and tag me I can take a look
