### ISSUE TITLE
Group 1 : separation-of-concerns , week 2

### ISSUE THREAD

**Issue by KrystynaMil** [HackYourFutureBelgium/class-11-12#237]
#  The JavaScript 30

- _Group 1_
- _@KrystynaMil_
- _@rago89_
-  _@DIVYASREE345_
- _@Brainketunze_

- [x] 11: Custom Video Player
- [x] 15: localStorage

---
11: Custom Video Player
- [x] [repo](https://github.com/rago89/custom-video-player) with a complete README
- [x] [live demo](https://rago89.github.io/custom-video-player/)
- [x] [project-planning](https://github.com/rago89/custom-video-player/tree/main/planning)
- [x] [A project board](https://github.com/rago89/custom-video-player/projects/1)
- [x] [One issue per task](https://github.com/rago89/custom-video-player/issues)
- [x] [One branch per issue](https://github.com/rago89/custom-video-player/network)
- [x] [One reviewed PR per completed issue](https://github.com/rago89/custom-video-player/pulls?q=is%3Apr+is%3Aclosed)
--- 
15: localStorage
- [x] [repo](https://github.com/KrystynaMil/localStorage) with a complete README
- [x] [live demo](https://krystynamil.github.io/localStorage/)
- [x] [project-planning](https://github.com/KrystynaMil/localStorage/tree/master/project-planning)
- [x] [A project board](https://github.com/KrystynaMil/localStorage/projects/1)
- [x] [One issue per task](https://github.com/KrystynaMil/localStorage/issues) (with labels and milestones)
- [x] [One branch per issue](https://github.com/KrystynaMil/localStorage/network)
- [x] [One reviewed PR per completed issue](https://github.com/KrystynaMil/localStorage/pulls?q=is%3Apr+is%3Aclosed)
---

**Comment by samirm00** [comment]
Dear colleague , you suppose to do only one challenge , I asked  Evan  , and he told me you can choose one of the five above ,  
you can just refactor your code or if you want you can refactor it and add more feature  , regards ,
