### ISSUE TITLE
Incremental development, week 1, Sunday Roll Call

### ISSUE THREAD

**Issue by unmeshvrije** [HackYourFutureBelgium/class-11-12#42]
## Roll Call!

Leave us a comment with these two things:

1. A summary of your week using only emojis
2. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by krakla** [comment]
🤓🏃🏽‍♂️🍗😴🤒💻🖥💻🖥😏😱🥴🧐🤞🤞📚📖📚📖💻

**Comment by samirm00** [comment]
:smiley: Hey

**Comment by AnisyaPurnama** [comment]
1. 💭 🤔 👍 
2. so far so good.

**Comment by Atinos31** [comment]
1.😟😇🤓
2. ready  for today's session.

**Comment by sabanyelkenci** [comment]
:mask: Hi everyone

**Comment by emelysalmeron** [comment]
> 🏃🏻‍♀️🏃🏻‍♀️➡️⬅️➡️⬅️➡️⬅️

**Comment by preeti-t** [comment]
😃 Hello every one.
It was fun in first session, excited for the next one.

**Comment by SolomunWelday** [comment]
I like it, i work on git, github and how to create repository and push and pull from each other. good start, i only have some problem in gitkraken, i would like if the coach revise it. Thank you!

**Comment by LiubovPlugar** [comment]
hey

**Comment by rago89** [comment]
Good morning ready to work :muscle:

**Comment by himanshisaxena** [comment]
Hello

**Comment by DIVYASREE345** [comment]
😃 
so far  it was fun...

**Comment by krakla** [comment]
🏃🏽‍♂️

**Comment by peymanshahmarimikaeeldarehsi** [comment]
hey

**Comment by businan** [comment]
Hi everyone,
Are we ready for class

**Comment by tahminarasoli** [comment]
Hello everyone!

**Comment by bermarte** [comment]
Hello there.  :innocent:

**Comment by jraoul2002** [comment]
hi there

**Comment by Houcinos** [comment]
🤪 Discovering

**Comment by Ina-arpine** [comment]
hi

**Comment by Moon-NguyetDuong** [comment]
1. 😇 🤔 😟🤯 
2. It was a super busy week for me. I have just started a part-time job, I am now working 20 hours a week, with a small baby, I could rarely find time to study, and I already feel so behind with the coding journey... 😞 😢 🤯

**Comment by kemmy72** [comment]
Hello, I'm coping

**Comment by KrystynaMil** [comment]
😀

**Comment by himanshisaxena** [comment]
Hello
