### ISSUE TITLE
Anisya : Incremental Development

### ISSUE THREAD

**Issue by AnisyaPurnama** [HackYourFutureBelgium/class-11-12#44]
## Suggested Study

- [x] Incremental Development
- [x] Git & GitHub
- [x] Command Line Interface
- [x] Wireframes
- [x] Writing READMEs
- [x] DevTools and the DOM
- [x] HTML & CSS
- [x] Collaborating on GitHub

## Exercises (Week 1)

- [x] [repo](https://github.com/AnisyaPurnama/acme-web-design) (with a complete README)
- [x] [live demo](https://anisyapurnama.github.io/acme-web-design/index.html)
- [x] [development strategy](https://github.com/AnisyaPurnama/acme-web-design/blob/master/my-dev-strategy.md)
- [x] [one branch per step](https://github.com/AnisyaPurnama/acme-web-design/branches)
- [x] [one closed PR per step](https://github.com/AnisyaPurnama/acme-web-design/pulls)
---

#### Learn a basic branching workflow:

- [x] 0. set up your repository and clone it
- [x] 1. write a development strategy
2. for each step : 
- [x] create a new branch locally
- [x] write your new code on that branch
- [x] push the branch to your repository
- [x] create a PR & merge the branch to master
- [x] pull the new master branch to your computer
- [x] continue to the next step

- [x] Sunday Prep

- [x] Sunday Class
[Sunday Class Project Link 27/09/2020](https://github.com/AnisyaPurnama/PinkPanther)

### Progress
* The branches and the codes of my repo are quite messy. After a few mistakes and conflict that I've made by making many commits on the master, I keep trying and trying to figure it out how the project suppose to be. Finally in the last few hours (today) I understand and manage to make some changes on the branches, push and pull it to the master. And finally my live demo also shown right.
* Wireframe in URL link format instead of .png or .img

### Next Steps
Keep exercising using the terminal, continue the suggested study. Exercising HTML and CSS more.
 
### Tip(s) of the week

Before making commit make sure that you are in the right branch. 

---

## Exercises (Week 2)
- [x] [repo](https://github.com/AnisyaPurnama/app-theme) (with a complete README)
- [x] [live demo](https://anisyapurnama.github.io/app-theme/)
- [x] [development strategy](https://github.com/AnisyaPurnama/app-theme/blob/master/development-strategy.md)
- [x] [project board w/ labeled issues](https://github.com/AnisyaPurnama/app-theme/projects)
- [x] [issues closed by PRs](https://github.com/AnisyaPurnama/app-theme/issues)
- [x] [one branch per step](https://github.com/AnisyaPurnama/app-theme/network)
- [x] [one closed PR per step](https://github.com/AnisyaPurnama/app-theme/pulls)

#### Learn to organize your progress with issues and a project board:

- [x] 1. set up your repository and clone it write a development strategy
- [x] 2. set up a project board on your repo
- [x] 3. create one issue per step, move them to the board
4. for each step :
- [x] move that issue into in progress
- [x] create a new branch locally
- [x] write your new code on that branch
- [x] push the branch to your repository
- [x] create a PR linked to this issue
- [x] move the issue to ready for review
- [x] merge the PR, closing this step's issue
- [x] move the issue into done
- [x] pull the new master branch to your computer
- [x] continue to the next step

- [x] Sunday Prep

- [x] Sunday Class
[Sunday Class Project Link 04/10/2020](https://github.com/AnisyaPurnama/PinkPanther/projects)

### Progress
* I finished my Sunday class project board exercise.
* Generate my repo from the template that given.
* Finally I finished my App-theme project including the Project board's, what a learning! 🙌  By doing this project I learn many new things, overall from all the mistakes that I made during the process.
* This time I managed to add my wireframe in png. file.

### Blocked
In the merging time to the master, (again) I got a few times conflicts and I need to rewrite some of codes. But then by explanation from Stephane I realize that I need to make sure that I'm Up-to-date to the `main` before creating a new branch. My conflicts is now solve.

### Next Steps
* Doing some more exercising writing the html and CSS code. 
* Read more about Github workflow
* Prepare for Sunday class
 
### Tip(s) of the week
Make sure that you already double check all your code before you push your changes. 
My mistake is I'm not thorough enough, so I have to commit my `finishing touch` more than one time. 😆  

---

## Exercises (Week 3)
- [x] [Group 1 Duck-duck-clone project](https://github.com/HackYourFutureBelgium/class-11-12/issues/102)

#### Learn to collaborate on one repository:

- [x] set up your repository and clone it
- [x] write a development strategy
- [x] set up a project board on your repo
- [x] create one issue per step, move them to the board
- [x] assign each issue to one group member
- [x] each group member codes their assigned issue
- [x] the group merges each others' pull requests one at a time

- [x] Sunday Prep

- [x] Sunday Class
[Sunday Class Project Link 11/10/2020](https://github.com/AnisyaPurnama/PinkPanther/projects/1)

### Progress
* My team leader Emely, generate the repo from the template that given.
* I made a new branch and create the html and CSS code there.
* Make Pull request to the master (waiting for review)

### Next Steps
* Doing some more exercising writing the html and CSS code. 
* Prepare for Sunday class
 
### Tip(s) of the week
🤔 
---
### What went well
* making the branch, pushing and pull request
* making the HTML file

### What went less well
* making the CSS file
*  group project merging to master

### What to do differently next module
* more careful in making code

### Shout-Out
thank you @krakla 

### Reflections
👁️‍🗨️

**Comment by AnisyaPurnama** [comment]
Dear @colevandersWands @talmurshidi , could you please give some feedback for me? it would really helpfull. 😊

**Comment by colevandersWands** [comment]
@AnisyaPurnama , sorry for the late check. Beautiful strategy and project board!  I only have two suggestions that will make it easier to collaborate next week:
1. Try to make more smaller steps. If you find that you're writing __and__ in one of your step titles, maybe that step should be two steps
2. Include CSS class names and selectors in your strategy.  This will make it possible for you to share one step between two people, one writes HTML the other writes CSS.  As long as you both use the correct class names and tags your code _should_ be able to merge with no large problems

💯

**Comment by AnisyaPurnama** [comment]
@colevandersWands noted! thank you 😊

**Comment by colevandersWands** [comment]
@AnisyaPurnama , could you share links to the code that has you blocked? It's hard to help without knowing more details.  You could also fill out a [help-wanted](https://github.com/HackYourFutureBelgium/class-11-12/issues/new?assignees=&labels=help-wanted&template=i-need-help.md&title=)  issue and share that on the class channel

**Comment by AnisyaPurnama** [comment]
@colevandersWands Thanks Evan, in the meantime it already solve! @krakla helped me. 😁
