### ISSUE TITLE
rago89: Incremental Development

### ISSUE THREAD

**Issue by rago89** [HackYourFutureBelgium/class-11-12#45]
# Assignment individual  Project

- [x] study and reverse-engineer the [__acme-web-design__ tutorial from Traversy Media](https://www.youtube.com/watch?v=Wm6CUkswsNw).

- [x] Writing the same code as Mr. Traversy's code is not enough! You are expected to submit your code from his tutorial in a new repository on your GitHub account using [this starter repository](https://github.com/HackYourFutureBelgium/w3-validation-template).  Your repository should be named `acme-web-design` and should be cleanly developed with one branch per step.  It's up to you to write the development strategy!

- [x]  follow the tutorial studying the code and understanding the project.
- [x]  look over your finished code and break it down into steps, write your development strategy.
- [x]  study the tutorial a second time, following your strategy to build your repository one branch at a time

## Pay attention 

> You will be assessed not only on your live demo, but also on the quality of your code, your development strategy, the correctness of your branches, and the completeness of your repository. 

## Review to fix from @snicoll 

- [x] Your description misses the reference for the team branchies project (pink panther)
- [x] The Acme web design rendering must have a header that allows coaches to validate your CSS and your HTML but that's missing for you
- [x]  Your development strategy should have one section per step (per branch) and each of them should be explained in detail. I know this sounds a bit silly but the objective here is to get used to decompose a goal into smaller tasks up front and then execute the plan
- [x] Your default branch should be `master`, not `gh-pages`. There is a way to enable gh-pages in your repository

## Progress status 
- [x] [repo pinkpanther](https://github.com/rago89/pinkpanther)
- [x] [repo](https://github.com/rago89/acme-web-design) (with a complete README)
- [x] [live demo](https://rago89.github.io/acme-web-design/.)
- [x] [development strategy](https://github.com/rago89/acme-web-design/blob/master/development-strategy..md)
- [x] [one branch per step](https://github.com/rago89/acme-web-design/branches)
- [x] [one closed PR per step](https://github.com/rago89/app-theme/pulls?q=is%3Apr+is%3Aclosed)

- [x] Sunday Prep
- [Git & GitHub for Poets](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV): 1.4
- GitHub
  - [Pull Requests](https://www.youtube.com/watch?v=2M16faxEQsg)
  - linking PRs to Issues: [reference 1](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue),  [reference 2](https://help.github.com/articles/autolinked-references-and-urls/)
  - [closing Issues using keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords)
- [from-strategy-to-issues](https://github.com/hackyourfuturebelgium/from-strategy-to-issues) (example repository)

- [x] Sunday Class

### Progress
learned, agile development, create a development strategy, create a readme, branching, rebase with branching, command cherry-pick, work in responsive web design with @media queries
### Blocked
undone work pushed, and committed locally.
### Next Steps
Learn pull request, link PR to an issue, add collaborators, closing issues with keywords
### Tip(s) of the week
work with [Git Learn Branching](https://learngitbranching.js.org/)
---

### Suggested Study

1. This week's project is to study the [__app-theme__ tutorial from Traversy Media](https://www.youtube.com/watch?v=qlA7dputiNc).

Writing the same code as Mr. Traversy's code is not enough! You are expected to submit your code from his tutorial in a new repository on your GitHub account [forked](https://guides.github.com/activities/forking/) from [this starter template](https://github.com/HackYourFutureBelgium/w3-validation-template).  Your repository should be named `app-theme` and should be cleanly developed with one branch per step.  It's up to you to write the development strategy!

* A good strategy for completing this project is the __three-step__:

1. follow the tutorial studying the code and understanding the project.
2. look over your finished code and break it down into steps, write your development strategy.
3. study the tutorial a second time, following your strategy to build your repository one branch at a time

>You will be assessed not only on your live demo, but also on the quality of your code, your development strategy, the correctness of your branches, and the completeness of your repository. Your repository must contain:

### Exercises

- [x] [repo](https://github.com/rago89/app-theme) (with a complete README)
- [x] [live demo](https://rago89.github.io/app-theme/.)
- [x] [development strategy](https://github.com/rago89/app-theme/blob/master/development-strategy.md)
- [x] [project board w/ labeled issues](https://github.com/rago89/app-theme/projects/1?add_cards_query=is%3Aopen)
- [x] [issues closed by PRs](https://github.com/rago89/app-theme/issues?q=is%3Aissue+is%3Aclosed)
- [x] [one branch per step](https://github.com/rago89/app-theme/branches)
- [x] [one closed PR per step](https://github.com/rago89/app-theme/pulls)

---
### Prep Work

> before class

- [Git Workflow for Two](https://github.com/hackyourfuturebelgium/git-workflow-workshop-for-two)
- [about code reviews](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews)
- [requesting a code review](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review)
- [from-strategy-to-issues](https://github.com/hackyourfuturebelgium/from-strategy-to-issues) (example repo)

- [x] Sunday Prep

- [x] Sunday Class

### Progress
Workin responsive web design with **flexbox grid**, work on a project,  improving Development Strategy, improving Wireframes, 
### Blocked
Everything it's ok.
### Next Steps
Learn about the DOM, Git workflow, work about code reviews, requesting code reviews, resolving conflicts. keep learning more git commands.
### Tip(s) of the week
 [Good video to understand rebase](https://www.youtube.com/watch?v=f1wnYdLEpgI/)

### Suggested Study

- Collaborating on GitHub
  - [about code reviews](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews)
  - [requesting a code review](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review)
  - [Git Workflow for 2](https://github.com/hackyourfuturebelgium/git-workflow-workshop-for-two)
  - [Pull Requests](https://www.youtube.com/watch?v=2M16faxEQsg)
  - Git & GitHub for Poets: [pull request & merge](https://www.youtube.com/watch?v=_NrSWLQsDL4&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV&t=0s), [resolving conflicts](https://www.youtube.com/watch?v=JtIX3HJKwfo)
  - The Net Ninja: [11](https://www.youtube.com/watch?v=MnUd31TvBoU&list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR&index=11)
  - linking PRs to Issues: [reference 1](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue),  [reference 2](https://help.github.com/articles/autolinked-references-and-urls/)
  - [closing Issues using keywords](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords)
---
## Week's project

week's _**group**_ project is to build your own accessible & responsive clone of the [DuckDuckGo home page](https://duckduckgo.com/?va=z&t=hr) (long version).  We don't expect your DOM to be identical to DuckDuckGo's, or for all the buttons to have the same behavior, but visually your site should be identical to the real DuckDuckGo.  If you would like to use a CSS framework, go for it! Just be sure everyone in your team uses it ;)

Unlike the last two weeks, this project does not have a video tutorial for you to follow. This week you will also be expected to do your best at writing _accessible_ HTML including correct Semantic HTML and ARIA. Pay special attention to points of user interaction like the search field and submit button.

You are expected to submit your code from his tutorial in a new repository [generated](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/) from [the w3-validation-starter repo](https://github.com/HackYourFutureBelgium/w3-validation-template).  Your repository should be named `duck-duck-clone` and should be collaboratively developed following the same workflow you practiced in class this Sunday.  It's up to you to write the development strategy!

### Issue Checklist

[Project](https://github.com/rago89/DuckDuckGoGroup6) (with a complete README)

[Projects's Issue](https://github.com/HackYourFutureBelgium/class-11-12/issues/99)
### What went well
Went well with issues, working with terminal creating folders, files working with Git, creating branches, making commits, cloning, pulling, pushing, working with teams in the project, it has been a lot of good things.
### What went less well
Working learning how to revert mistakes, would be nice to add more content, now it's perfect that we start making a lot of mistakes
### What to do differently next module
Improve the way os study, improve mi CSS 
### Reflections
is not easy but also is not impossible is others can do it I also can do it

**Comment by snicoll** [comment]
@rago89 thank for sharing your progress. Note that's the issue for week 1, not week 2 (it should have been created prior to class last Sunday).

Some initial feedback:

* Your description misses the reference for the team branchies project (pink panther)
* The Acme web design rendering must have a header that allows coaches to validate your CSS and your HTML but that's missing for you
* Your development strategy should have one section per step (per branch) and each of them should be explained in details. I know this sounds a bit silly but the objective here is to get used to decompose a goal into smaller tasks upfront and then execute the plan
* Your default branch should be `master`, not `gh-pages`. There is a way to enable gh-pages in your repository

Great progress, can you please review the following and update your description? Let me know if you have any questions!

**Comment by snicoll** [comment]
I forgot to mention something. Updating this of course doesn't require you to redo all your branches. Please push additional commit to `master` directly so that we can continue the review.

**Comment by rago89** [comment]
> @rago89 thank for sharing your progress. Note that's the issue for week 1, not week 2 (it should have been created prior to class last Sunday).
> 
> Some initial feedback:
> 
> * Your description misses the reference for the team branchies project (pink panther)
> * The Acme web design rendering must have a header that allows coaches to validate your CSS and your HTML but that's missing for you
> * Your development strategy should have one section per step (per branch) and each of them should be explained in details. I know this sounds a bit silly but the objective here is to get used to decompose a goal into smaller tasks upfront and then execute the plan
> * Your default branch should be `master`, not `gh-pages`. There is a way to enable gh-pages in your repository
> 
> Great progress, can you please review the following and update your description? Let me know if you have any questions!



> @rago89 thank for sharing your progress. Note that's the issue for week 1, not week 2 (it should have been created prior to class last Sunday).
> 
> Some initial feedback:
> 
> * Your description misses the reference for the team branchies project (pink panther)
> * The Acme web design rendering must have a header that allows coaches to validate your CSS and your HTML but that's missing for you
> * Your development strategy should have one section per step (per branch) and each of them should be explained in details. I know this sounds a bit silly but the objective here is to get used to decompose a goal into smaller tasks upfront and then execute the plan
> * Your default branch should be `master`, not `gh-pages`. There is a way to enable gh-pages in your repository
> 
> Great progress, can you please review the following and update your description? Let me know if you have any questions!

**Ready dor a new review**

**Comment by colevandersWands** [comment]
Hello @rago89 , I've removed your `check-in-2` label for now because it looks like you didn't write a check-in for this week?

After you've answered the check-in questions for this week (progress, blocked, next steps, tip(s)) let us know by putting the `check-in-2` label back on your issue.

**Comment by rago89** [comment]
> Hello @rago89 , I've removed your `check-in-2` label for now because it looks like you didn't write a check-in for this week?
> 
> After you've answered the check-in questions for this week (progress, blocked, next steps, tip(s)) let us know by putting the `check-in-2` label back on your issue.

Sorry for not seen it, already added, thanks for noted

**Comment by colevandersWands** [comment]
@rago89 , beautiful check-in!  Happy to see nothing is blocking you yet.  Don't hesitate to mention one of us as soon as this changes. 🐎

**Comment by snicoll** [comment]
Nice work this week again @rago89. I've added a few hints in your issue, feel free to reach out if you have any questions!

**Comment by rago89** [comment]
> Nice work this week again @rago89. I've added a few hints in your issue, feel free to reach out if you have any questions!

Thanks for reviewing, I will take a look.

**Comment by colevandersWands** [comment]
> is not easy but also is not impossible is others can do it I also can do it

💯 

@rago89 , nice work this module getting used to Git and project planning. And thank you for taking the lead and helping out in your team.
