### ISSUE TITLE
LiubovPlugar: Incremental development-week 1

### ISSUE THREAD

**Issue by LiubovPlugar** [HackYourFutureBelgium/class-11-12#51]
## Exercises

---

## Week X

- [ ] Sunday Prep

- [ ] Sunday Class

### Tip(s) of the week

---

**Comment by bermarte** [comment]
Hi this is just a friendly remark. I'm pretty sure you should fill out this template and I'm not sure it's up to us to close this issue. However, you can still reopen and refill it. If it wasn't closed, I would think you may be planning to fill it up later.
