### ISSUE TITLE
jraoul2002: incremental development

### ISSUE THREAD

**Issue by jraoul2002** [HackYourFutureBelgium/class-11-12#59]
## Suggested Study

- [x] Git & GitHub
- [x] Command Line Interface
- [ ] Wireframes
- [ ] Writing READMEs
- [ ] HTML & CSS

## Exercises

- [x] set up your repository and clone
- [x] write a development strategy
For each step
 - [x] create a new branch locally
- [x]  write your new code on that branch
 - [x] push the branch to your repository
 - [x] create a PR & merge the branch to master
 - [x] pull the new master branch to your computer
 continue to the next step

---

## Week 1

- [x] Sunday Prep

- [x] Sunday Class

- [x] [repo](https://github.com/jraoul2002/acme-web-design) 
- [x] [live demo](https://jraoul2002.github.io/acme-web-design) 
- [x] [development strategy](https://github.com/jraoul2002/acme-web-design/blob/master/dev-strategy.md)
- [x] [one branch per step](https://github.com/jraoul2002/acme-web-design/branches )
- [x] [one closed PR per step](https://github.com/jraoul2002/acme-web-design/pulls)

### Tip(s) of the week

---

### What went well
actually i didnot face a big problem

### What went less well
Writing down the development strategy

**Comment by colevandersWands** [comment]
@jraoul2002 , can you fill in the sections for the week 1 check-in?  adding the label without also sharing your progress is not a full check-in

**Comment by jraoul2002** [comment]
Do you mean to answer to this : 
Progress
Blocked
Next Steps
Tip(s) of the week

and so on ... .

**Comment by colevandersWands** [comment]
@jraoul2002 , exactly.  It's hard to know how you're doing if you don't tell us !

**Comment by jraoul2002** [comment]
it is done.. i think  but yesterday i had a talk with Mary and i had someextra informations and i did judge that it was not necessary to write down(here) since   i could go further with my work. But for the next homework i will follow all the steps 😄

**Comment by colevandersWands** [comment]
If there are no problems then just write that,  to go one step further it can be helpful to say what you were blocked on and how you figured it out.  A totally empty check-in looks like you haven't been doing anything.
