### ISSUE TITLE
Emely Salmeron: Incremental Development - w2

### ISSUE THREAD

**Issue by emelysalmeron** [HackYourFutureBelgium/class-11-12#78]
## Suggested Study
- [x] Git & GitHub for Poets: 1.4
- [ ] GitHub
- [ ] Pull Requests
- [ ] Linking PRs to Issues: reference 1, reference 2
- [ ] closing Issues using keywords
- [ ] from-strategy-to-issues (example repository)

A good strategy to for completing this project is the three-step:

follow the tutorial studying the code and understanding the project.
look over your finished code and break it down into steps, write your development strategy.
study the tutorial a second time, following your strategy to build your repository one branch at a time

## Exercises

- [x] [repo](https://github.com/emelysalmeron/app-theme) (with a complete README)
- [ ] [live demo](https://emelysalmeron.github.io/app-theme/)
- [ ] [development strategy](https://github.com/_/_/tree/master/development-strategy.md)
- [ ] [project board w/ labeled issues](https://github.com/_/_/projects/1)
- [ ] [issues closed by PRs](https://github.com/_/_/issues)
- [ ] [one branch per step](https://github.com/_/_/network)
- [ ] [one closed PR per step](https://github.com/_/_/pulls)
---

## Week 2

- [ ] Sunday Prep

- [ ] Sunday Class

### Tip(s) of the week

---

**Comment by colevandersWands** [comment]
@emelysalmeron, this is a duplicate issue for Incremental Development.  You've already created one last week, for this week all you need to do is add in a __Week 2__ section.   [this example issue](https://github.com/HackYourFutureBelgium/class-11-12/issues/88) may help you find your way around this process

**Comment by emelysalmeron** [comment]
@colevandersWands Understood! Thank you Evan.
