### ISSUE TITLE
SolomunWelday: Incremental Development 

### ISSUE THREAD

**Issue by SolomunWelday** [HackYourFutureBelgium/class-11-12#87]
## Suggested Study
<a href="https://www.youtube.com/watch?v=qlA7dputiNc">Build A Responsive HTML & CSS Template With FlexboxGrid</a>

## Exercises

- [ ]  <a href="https://github.com/SolomunWelday/app-theme">App-Theme Repo</a>
- [ ] <a href="https://solomunwelday.github.io/app-theme/">Version 0.1</a>
- [ ] <a href="https://github.com/SolomunWelday/app-theme/edit/main/development-strategy.md">Initial Version of the 
Development Strategy </a> 
- [ ] <a href="https://github.com/SolomunWelday/app-theme/issues">Issues</a>

---

## Week X

- [ ] Sunday Prep

- [ ] Sunday Class 

### Tip(s) of the week

---

### Reflections

**Comment by bermarte** [comment]
I have added the label **check-in-2** for you, Solomon.
