### ISSUE TITLE
Incremental Development, week 3, Sunday Roll Call

### ISSUE THREAD

**Issue by colevandersWands** [HackYourFutureBelgium/class-11-12#94]
## Roll Call!

Leave us a comment with these two things:

1. A summary of your week using only emojis
1. Something you'd like to share, anything goes! (within respect)

> [emoji cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet)

**Comment by krakla** [comment]
😁
I miss Sunday class. I had a week without laptop 😒. Yesterday evening I fixed the problem and will launch like a rocket🚀 😂

**Comment by sharafcs50** [comment]
1) 😃 📖 💻 
2) Time to study harder, have been looking at the material ahead and some serious study is required.

**Comment by businan** [comment]
Hi everyone. Time to write a code

**Comment by AnisyaPurnama** [comment]
1. :thinking: :cowboy_hat_face: :monocle_face:
2. Getting more challenging! Ready for the next one!

**Comment by lauraramirez220612** [comment]
1.😪😷🥰
2.  Yesterday I did all I could in my assignment, not yet finished, sorry

**Comment by jraoul2002** [comment]
😁 
Hi mates it was a busy week for me but Time to code now 👊

**Comment by otagi** [comment]
💻 🌦️ 
Who's ready to become a Git(Hub) virtuoso? 😄

**Comment by DIVYASREE345** [comment]
1. 🤢 😷 
2. Ready for first group work...

**Comment by LiubovPlugar** [comment]
:open_mouth: but :+1:

Classmates helping, coaches helping - thanks everybody for fast reaction

**Comment by samirm00** [comment]
:smiley:   [How to squash git commits ](https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc)

**Comment by iLienstAr** [comment]
Good luck with class today and with your first group project!

**Comment by preeti-t** [comment]
Hi everyone. 
1. 👍 😪🥰
2.  Learning during the week is sometimes interesting and sometimes challenging.

**Comment by Houcinos** [comment]
😕 
Got stuck in an issue with gitbash for 3 days. Please take into consideration people with NO background with these stuff. It might seem easy or obvious for most of you but not for everyone. 
-> Special thanks for Stephane and Samir

**Comment by KrystynaMil** [comment]
1. :) 
2. Good Morning :) Ready for Sunday work and first group project !

**Comment by bermarte** [comment]
:persevere:  :no_mouth:  :speech_balloon:  :umbrella:  :bread:  :house:  :fuelpump:  :beginner:

**Comment by rago89** [comment]
:smiley: :mask: :nerd_face: :mechanical_arm:
Has been a very good week, is not easy but also is not impossible.

**Comment by Brainketunze** [comment]
😅 🤔 💻 
To be a sucessful man/woman, in live you need to work very hard in all your doings.

**Comment by peymanshahmarimikaeeldarehsi** [comment]
hello 
previous week it was good i learn a lot of things like project board on git hub and flexibox grid tutorial ,but i did not finish my exercises cause i saw last exercises very late ,i hope lien do not check my git hub, i will try to complate it till tonight.

**Comment by iLienstAr** [comment]
@peymanshahmarimikaeeldarehsi you hope I don't check your GitHub? I won't be mad if you don't finish the exercises 😄 don't worry. You're working hard and that's what matteres to HackYourFuture.

**Comment by kemmy72** [comment]
Still learning

**Comment by tahminarasoli** [comment]
😃
It's a great oppotunity for me and I try harder each and every week to make sure I am using it properly.

**Comment by Ina-arpine** [comment]
first was hard and then by trying a lot and with the help of my team  I find the solution

**Comment by peymanshahmarimikaeeldarehsi** [comment]
@iLienstAr thank you lien i promise work harder😃

**Comment by emelysalmeron** [comment]
1. 💯
2. My wifi has been my struggle

**Comment by Atinos31** [comment]
🤨😮😑🙄😏
my week was fine..cold , sickly but i still have issues using git.

**Comment by MarieBelyse** [comment]
First week was hard for but now I start to understand a bit.
