### ISSUE TITLE
Group 6: Incremental Development , week 3

### ISSUE THREAD

**Issue by rago89** [HackYourFutureBelgium/class-11-12#99]
#  DuckDuckGoGroup6
- _team name_
Group 6

- _project leader_

[rago89](https://github.com/rago89)

- _repository owner_

[rago89](https://github.com/rago89)

This is a web site recreated from the home page [DuckDuckGo](https://duckduckgo.com/?va=z&t=hr&atb=v214-1), this web is recreated by the Group 6 of [HackYourFutureBelgium](https://hackyourfuture.be/) class-11-12 from the second module called [Incremental Development](https://github.com/HackYourFutureBelgium/incremental-development)

- [x] [repo](https://github.com/rago89/-DuckDuckGo) (with a complete README)
- [x] [live demo](https://rago89.github.io/DuckDuckGoGroup6/)
- [x] [development strategy](https://github.com/rago89/DuckDuckGoGroup6/blob/main/Developmet-Strategy.md)
- [x] [project board w/ labeled & assigned issues](https://github.com/rago89/DuckDuckGoGroup6/projects/1)
- [x] [issues closed by PRs](https://github.com/_/_/issues)
- [x] [one branch per step](https://github.com/rago89/DuckDuckGoGroup6/branches)
- [x] [one closed PR per step](https://github.com/_/_/pulls)
- [x] [multiple contributors](https://github.com/rago89/DuckDuckGoGroup6/graphs/contributors)

**Comment by samirm00** [comment]
Hey @rago89  Labels: group, project-x (both placed when the issue is created)(x for the number of the week we're in)
I guess the correct labels are group and project-3  according to above .
Best regards,

**Comment by rago89** [comment]
thanks for the suggestion

**Comment by samirm00** [comment]
Dear colleagues , your issue doesn't appear in the project board  .

**Comment by samirm00** [comment]
Dear colleagues , I have select the project for you , so your issue will appears in the project board . kind regards,
